### PR TITLE
Mark conda-build 3.28.3 broken

### PR DESCRIPTION
**Pull request by minrk**
3.28.3 cannot build multi-output recipes due to overlinking detection bug, reported upstream: https://github.com/conda/conda-build/issues/5136

cc @conda-forge/conda-build

Successful output with 3.28.2:

```
   INFO: sysroot: '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1704716089790/_build_env/x86_64-conda-linux-gnu/sysroot/' files: '['/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1704716089790/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/zone.tab', '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1704716089790/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/tzdata.zi', '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1704716089790/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/Zulu', '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1704716089790/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/WET']'
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libdolfinx_mpc.so.0.7 found in local/linux-64::libdolfinx_mpc==0.7.2=h26ae040_0
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libdolfinx.so.0.7 found in conda-forge/linux-64::fenics-libdolfinx==0.7.2=h5817365_3
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libmpi.so.12 found in conda-forge/linux-64::mpich==4.1.2=h846660c_101
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libpetsc.so.3.20 found in conda-forge/linux-64::petsc==3.20.3=complex_hb8e3d0a_0
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libstdc++.so.6 found in conda-forge/linux-64::libstdcxx-ng==13.2.0=h7e041cc_3
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libm.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_16
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-64::libgcc-ng==13.2.0=h807b86a_3
   INFO (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_16
```

failed output with no changes other than conda-build version 3.28.3:

```
   INFO: sysroot: '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1705322752890/_build_env/x86_64-conda-linux-gnu/sysroot/' files: '['/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1705322752890/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/zone.tab', '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1705322752890/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/tzdata.zi', '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1705322752890/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/Zulu', '/home/conda/feedstock_root/build_artifacts/dolfinx_mpc-split_1705322752890/_build_env/x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/WET']'
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): lib/libdolfinx_mpc.so.0.7 not found in any packages
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): lib/libdolfinx.so.0.7 not found in any packages
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): lib/libmpi.so.12 not found in any packages
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): lib/libpetsc.so.3.20 not found in any packages
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): lib/libstdc++.so.6 not found in any packages
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libm.so.6 not found in any CDT/compiler package, nor the whitelist?!
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): lib/libgcc_s.so.1 not found in any packages
  ERROR (dolfinx_mpc,lib/python3.10/site-packages/dolfinx_mpc/cpp.cpython-310-x86_64-linux-gnu.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 not found in any CDT/compiler package, nor the whitelist?!
```

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

* [ ] I want to request (or revoke) access to an opt-in CI resource:
  * [ ] Pinged the relevant feedstock team(s)
  * [ ] Added a small description explaining why access is needed

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
This will cause a critical performance regression.

**Comment by minrk** [comment]
If there's a workaround, that would be great! But right now, 3.28.3 can't build multi-output packages. That seems worse than performance being the same as it was a week ago. But if performance is more important, how should packages get updates while 3.28.3 can't build them?

**Comment by beckermr** [comment]
One should be able to specify requirements for the ci in the conda forge yaml. Try this one https://conda-forge.org/docs/maintainer/conda_forge_yml.html#remote-ci-setup

**Comment by minrk** [comment]
Thanks! I think I can work with that. I think perhaps adding

```python
build:
  overlinking_ignore_patterns:
    - "*"
```

should also work and not require a rerender.

In the meantime, I believe https://github.com/conda/conda-build/pull/5138 fixes the root cause issue.

**Pull request closed without merging**
