### PR TITLE
Reset Azure token for `loopy`

### PR DESCRIPTION
**Pull request by jakirkham**
Seeing issues uploading: https://github.com/conda-forge/loopy-feedstock/pull/6#issuecomment-1949935801

Also looks like the PR template no longer has a reset token option?

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...looks like this didn't work. Not sure what is happening here

```python
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/site-packages/conda_smithy/ci_register.py", line 96, in travis_headers
No circle token.  Create a token at https://circleci.com/account/api and
    with open(travis_token, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.conda-smithy/travis.token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/site-packages/conda_smithy/github.py", line 18, in gh_token
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.conda-smithy/github.token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/admin-requests/admin-requests/conda_forge_admin_requests/token_reset.py", line 135, in run
    reset_feedstock_token(feedstock, skips=skips)
  File "/home/runner/work/admin-requests/admin-requests/conda_forge_admin_requests/token_reset.py", line 63, in reset_feedstock_token
    repo_info = travis_get_repo_info("conda-forge", name + "-feedstock")
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/site-packages/conda_smithy/ci_register.py", line 351, in travis_get_repo_info
    headers = travis_headers()
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/site-packages/conda_smithy/ci_register.py", line 108, in travis_headers
    data = {"github_token": github.gh_token()}
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/site-packages/conda_smithy/github.py", line 29, in gh_token
    raise RuntimeError(msg)
RuntimeError: No github token. Go to https://github.com/settings/tokens/new and generate
a token with repo access. Put it in ~/.conda-smithy/github.token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/share/miniconda3/envs/cf/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/admin-requests/admin-requests/conda_forge_admin_requests/__main__.py", line 74, in <module>
    run()
  File "/home/runner/work/admin-requests/admin-requests/conda_forge_admin_requests/__main__.py", line 45, in run
    try_again = getattr(actions[action], "run")(request)
  File "/home/runner/work/admin-requests/admin-requests/conda_forge_admin_requests/token_reset.py", line 141, in run
    feedstocks_to_do_again.append(pkg)
NameError: name 'pkg' is not defined
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No drone token. Create a token at https://cloud.drone.io/account and
Put one in ~/.conda-smithy/drone.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
failed to reset token for 'loopy': RuntimeError('No github token. Go to https://github.com/settings/tokens/new and generate\na token with repo access. Put it in ~/.conda-smithy/github.token')
```

Here is [the GHA log]( https://github.com/conda-forge/admin-requests/actions/runs/7941203996/job/21683306883#step:8:21 )

**Comment by jakirkham** [comment]
Looks like there was a bug. Undefined `pkg` variable. Fixing with PR: https://github.com/conda-forge/admin-requests/pull/940

**Comment by jakirkham** [comment]
Ran into another bug: https://github.com/conda-forge/admin-requests/pull/940#issuecomment-1949941110

Fixed in PR: https://github.com/conda-forge/admin-requests/pull/941

**Comment by jakirkham** [comment]
Unfortunately it looks like the token reset still did not work: https://github.com/conda-forge/admin-requests/commit/216909958335c83620d7eb8e61a3b4df799bc2d3

**Comment by beckermr** [comment]
This is fixed.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Fix is in PR: https://github.com/conda-forge/admin-requests/pull/942

**Pull request merged**
