### PR TITLE
Create  nvidia-apex.txt

### PR DESCRIPTION
**Pull request by rphel**
Hi!

These packages seem to be broken, I have described the issue in https://github.com/conda-forge/nvidia-apex-feedstock/issues/29

ping @conda-forge/nvidia-apex
ping @conda-forge/nvidia-apex-proc

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by jaimergp** [comment]
I can't reproduce locally:

```shell
$ CONDA_OVERRIDE_CUDA=11.2 CONDA_OVERRIDE_GLIBC=2.17 CONDA_SUBDIR=linux-64 micromamba create -n unused --dry-run nvidia-apex python=3.11                 

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

warning  libmamba 'root_prefix' set with default value: /Users/jrodriguez/micromamba
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
warning  libmamba linux version not found (virtual package skipped)

Transaction

  Prefix: /Users/jrodriguez/micromamba/envs/unused

  Updating specs:

   - nvidia-apex
   - python=3.11


  Package                Version  Build                     Channel                    Size
─────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex            0.1  conda_forge               conda-forge/linux-64        3kB
  + _openmp_mutex            4.5  2_kmp_llvm                conda-forge/linux-64        6kB
  + attrs                 22.2.0  pyh71513ae_0              conda-forge/noarch         54kB
  + bzip2                  1.0.8  h7f98852_4                conda-forge/linux-64      496kB
  + ca-certificates    2022.12.7  ha878542_0                conda-forge/linux-64      146kB
  + cffi                  1.15.1  py311h409f033_3           conda-forge/linux-64      296kB
  + colorama               0.4.6  pyhd8ed1ab_0              conda-forge/noarch         25kB
  + cudatoolkit           11.8.0  h37601d7_11               conda-forge/linux-64      667MB
  + cudnn               8.4.1.50  hed8a83a_0                conda-forge/linux-64      648MB
  + cxxfilt                0.3.0  py311ha362b79_4           conda-forge/linux-64       13kB
  + exceptiongroup         1.1.0  pyhd8ed1ab_0              conda-forge/noarch         19kB
  + icu                     70.1  h27087fc_0                conda-forge/linux-64       14MB
  + iniconfig              2.0.0  pyhd8ed1ab_0              conda-forge/noarch         11kB
  + ld_impl_linux-64        2.40  h41732ed_0                conda-forge/linux-64      705kB
  + libblas                3.9.0  16_linux64_openblas       conda-forge/linux-64       13kB
  + libcblas               3.9.0  16_linux64_openblas       conda-forge/linux-64       13kB
  + libffi                 3.4.2  h7f98852_5                conda-forge/linux-64       58kB
  + libgcc-ng             12.2.0  h65d4601_19               conda-forge/linux-64      954kB
  + libgfortran-ng        12.2.0  h69a702a_19               conda-forge/linux-64       23kB
  + libgfortran5          12.2.0  h337968e_19               conda-forge/linux-64        2MB
  + libhwloc               2.8.0  h32351e8_1                conda-forge/linux-64        3MB
  + libiconv                1.17  h166bdaf_0                conda-forge/linux-64        1MB
  + liblapack              3.9.0  16_linux64_openblas       conda-forge/linux-64       13kB
  + libnsl                 2.0.0  h7f98852_0                conda-forge/linux-64       31kB
  + libopenblas           0.3.21  pthreads_h78a6416_3       conda-forge/linux-64       11MB
  + libprotobuf          3.21.12  h3eb15da_0                conda-forge/linux-64        2MB
  + libsqlite             3.40.0  h753d276_0                conda-forge/linux-64      810kB
  + libstdcxx-ng          12.2.0  h46fd767_19               conda-forge/linux-64        4MB
  + libuuid               2.32.1  h7f98852_1000             conda-forge/linux-64       28kB
  + libxml2               2.10.3  h7463322_0                conda-forge/linux-64      773kB
  + libzlib               1.2.13  h166bdaf_4                conda-forge/linux-64       66kB
  + llvm-openmp           15.0.7  h0cdce71_0                conda-forge/linux-64        3MB
  + magma                  2.6.2  hc72dce7_0                conda-forge/linux-64      243MB
  + mkl                 2022.2.1  h84fe81f_16997            conda-forge/linux-64      165MB
  + nccl                2.14.3.1  h0800d71_0                conda-forge/linux-64      152MB
  + ncurses                  6.3  h27087fc_1                conda-forge/linux-64        1MB
  + ninja                 1.11.0  h924138e_0                conda-forge/linux-64        3MB
  + numpy                 1.24.2  py311h8e6699e_0           conda-forge/linux-64        8MB
  + nvidia-apex            22.03  cuda112py311h6c9afd8_1    conda-forge/linux-64      599kB
  + openssl                3.0.8  h0b41bf4_0                conda-forge/linux-64        3MB
  + packaging               23.0  pyhd8ed1ab_0              conda-forge/noarch         41kB
  + pluggy                 1.0.0  pyhd8ed1ab_5              conda-forge/noarch         16kB
  + pycparser               2.21  pyhd8ed1ab_0              conda-forge/noarch       Cached
  + pytest                 7.2.1  pyhd8ed1ab_0              conda-forge/noarch        237kB
  + python                3.11.0  he550d4f_1_cpython        conda-forge/linux-64       31MB
  + python_abi              3.11  3_cp311                   conda-forge/linux-64        6kB
  + pytorch               1.13.1  cuda112py311h13fee9e_200  conda-forge/linux-64      377MB
  + pyyaml                   6.0  py311hd4cff14_5           conda-forge/linux-64      207kB
  + readline               8.1.2  h0f457ee_0                conda-forge/linux-64      298kB
  + setuptools            67.1.0  pyhd8ed1ab_0              conda-forge/noarch        576kB
  + sleef                  3.5.1  h9b69904_2                conda-forge/linux-64        2MB
  + tbb                 2021.7.0  h924138e_1                conda-forge/linux-64        2MB
  + tk                    8.6.12  h27826a3_0                conda-forge/linux-64        3MB
  + tomli                  2.0.1  pyhd8ed1ab_0              conda-forge/noarch         16kB
  + tqdm                  4.64.1  pyhd8ed1ab_0              conda-forge/noarch         83kB
  + typing_extensions      4.4.0  pyha770c72_0              conda-forge/noarch         30kB
  + tzdata                 2022g  h191b570_0                conda-forge/noarch       Cached
  + xz                     5.2.6  h166bdaf_0                conda-forge/linux-64      418kB
  + yaml                   0.2.5  h7f98852_2                conda-forge/linux-64       89kB

  Summary:

  Install: 59 packages

  Total download: 2GB

─────────────────────────────────────────────────────────────────────────────────────────────

Dry run. Not executing the transaction.
```

I don't think the packages are broken.

**Comment by jakirkham** [comment]
Thanks Jaime! 🙏

Should we include that info in the issue as well?

**Comment by rphel** [comment]
I confirm it works with mamba (tested in the same environment) but the issue is with `conda`, not `mamba`.
The problem is that it is not possible to use mamba when building a package using `conda-build`.
As said in the issue, I am working behind a proxy and have no direct access to the conda-forge repository.
Can @jaimergp or someone test it also works with `conda` please? 😃

**Comment by mfansler** [comment]
I can confirm that `conda` throws `InvalidSpec` for these, e.g.,

```bash
CONDA_OVERRIDE_CUDA=11.2 CONDA_OVERRIDE_GLIBC=2.17 CONDA_SUBDIR=linux-64 conda create -n foo --dry-run nvidia-apex python=3.11
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): / WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py310hce0d3a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py38h73d78a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda102py39h4af2978_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py310h7cf977e_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py38hf5749dc_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda110py39h31ddb46_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py310h11f0b9a_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py38h7ba73a8_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda111py39h2dd2c40_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310h6ec7b7f_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py310hb11405b_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py311h6c9afd8_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hd717573_1 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py38hdf64721_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h83a068c_0 due to InvalidSpec: *=cuda
WARNING conda.core.index:push_record(246): Skipping conda-forge/linux-64::nvidia-apex-22.03-cuda112py39h955c134_1 due to InvalidSpec: *=cuda
done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

InvalidVersionSpec: Invalid version '*=cuda': invalid character(s)
```

However, that's a metadata issue and [the Conda Forge preference](https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages) is to patch the repository data rather than add the broken label.

**Comment by mfansler** [comment]
> "...it is not possible to use mamba when building a package using `conda-build`."

Not only is it possible, but that's what the Conda Forge CI uses. Specifically, it's provided by the `boa` package and invoked with `conda mambabuild` instead of `conda build`.

**Comment by JanuszL** [comment]
Hi,

Despite the package has been fixed, the old entries seem to still break the env - https://github.com/conda-forge/nvidia-apex-feedstock/issues/29#issuecomment-1459830380 and https://github.com/conda-forge/nvidia-apex-feedstock/issues/29#issuecomment-1462080052.
What we can do with that?

**Comment by jakirkham** [comment]
Think Mervin's comment above ( https://github.com/conda-forge/admin-requests/pull/674#issuecomment-1450540108 ) about a repodata hot-fix is still the best path forward. Is this something you are interested in helping with @JanuszL?

**Comment by JanuszL** [comment]
@jakirkham,

Let me check if I can figure out how to do this...

**Comment by JanuszL** [comment]
@jakirkham - just created https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/418.

**Comment by jakirkham** [comment]
Awesome thanks Janusz! :pray:

**Pull request closed without merging**
