### PR TITLE
remove freecad packages that uses wrong source-version

### PR DESCRIPTION
**Pull request by looooo**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [ ] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [ ] Added a description of the problem with the package in the PR description.
* [ ] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Please follow the instructions above on notifying teams and linking to issues on feedstocks. If you are the freecad team, then you can simply add that info.

**Comment by looooo** [comment]
@beckermr 
there were some commits backported lately. The mentioned builds do not use the final source. But the builds with build-number `3` should be identical to the older builds (regarding dependencies).
there is no reference issue, sorry.

Not sure what else I should do.

**Comment by beckermr** [comment]
Are the packages actually not functional for some reason?

cc @conda-forge/freecad for viz in case it is not @looooo

**Comment by looooo** [comment]
@beckermr it works, but is missing some backport commits.

**Comment by beckermr** [comment]
Wait are you saying upstream is backporting commits but not releasing new versions?

**Comment by beckermr** [comment]
We don't usually mark stuff broken if it functional and upstream has not pulled it.

**Comment by beckermr** [comment]
Upstream should be making patch releases when backporting and the e should be telling them that.

**Comment by looooo** [comment]
> Wait are you saying upstream is backporting commits but not releasing new versions?

sorry, we did some testing with the builds mentioned here. I know the workflow is not perfect, but adding a `broken` label to these builds is really the simplest way to proceed.

**Comment by beckermr** [comment]
Ok. Please use rc or dev releases on a label in the future.

**Pull request merged**
