### PR TITLE
Remove incorrectly named `python-gssapi` package

### PR DESCRIPTION
**Pull request by dhirschfeld**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by beckermr** [comment]
Please make sure to address the checklist above.

**Comment by dhirschfeld** [comment]
This package was added with the incorrect name. To avoid confusion with the conda-forge package not being the same as the pypi package it has been renamed in https://github.com/conda-forge/python-gssapi-feedstock/pull/1

**Comment by dhirschfeld** [comment]
Since the package is less than an hour old I'm pretty sure the only usages are from the related packages I've got on staged-recipes:

* https://github.com/conda-forge/staged-recipes/pull/12469
* https://github.com/conda-forge/staged-recipes/pull/12475

That being the case, I'd be happy for these packages to just be deleted.

**Comment by beckermr** [comment]
we don't delete things, but I am happy to merge this. the tests need to pass first though

**Comment by isuruf** [comment]
I'm not sure if `gssapi` is the best name here as it doesn't indicate that it's python. Is there a C/C++ package named `gssapi`?

**Comment by dhirschfeld** [comment]
I don't think there is a C/C++ project. To build the package it used the `krb5` package which provided the headers/libs for gssapi

**Comment by dhirschfeld** [comment]
The deprecated `python-gssapi` pypi package has the last version as 0.6.4 whereas the version of this package is 1.6.9. Since the old package will never publish another release there will never be any clashes so we could jsut leave the name as-is - thoughts?

**Comment by dhirschfeld** [comment]
I think I'm now inclined to leave it as is so I'll go ahead and close this. If there are any objections it can always be re-opened.

**Pull request closed without merging**
