### PR TITLE
Mark pangeo-forge-recipes 0.9.3 broken

### PR DESCRIPTION
**Pull request by cisaacstern**
## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by cisaacstern** [comment]
ping @conda-forge/pangeo-forge-recipes:

- `pangeo-forge-recipes==0.9.3` inadvertently introduced a hard dependency on `scipy`, when in fact the `scipy` dependency should be optional. Most importantly, `scipy` was not included in the requirements for this release (on PyPI or Conda Forge), so installing `0.9.3` results in a broken installation, which is only fixed if the user subsequently manually installs `scipy`.
- This was fixed by https://github.com/pangeo-forge/pangeo-forge-recipes/pull/466 (which also contains a longer discussion of the problem)
- `0.9.4` was released [on PyPI](https://pypi.org/project/pangeo-forge-recipes/) and [on `conda-forge`](https://anaconda.org/cf-staging/pangeo-forge-recipes/files?version=0.9.4)
- `0.9.3` was marked [yanked on PyPI](https://pypi.org/project/pangeo-forge-recipes/#history) and [in our release notes](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/development/release_notes.html#v0-9-3-2023-01-03)
- The [latest pangeo docker image tag now uses `0.9.4`](https://github.com/pangeo-data/pangeo-docker-images/pull/423)

I believe the last remaining clean up activity is this PR, which following the [docs here](https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages) is how we can prevent users from accidentally installing `0.9.3` via Conda Forge. I believe the next action here is to wait for the requested review to come through.

**Comment by ocefpaf** [comment]
@jaimergp looks like we have a glitch in the new archiving requests. I don't think it is related to this PR.

**Comment by jaimergp** [comment]
Yep, sorry about that. @cisaacstern can you rebase?

**Comment by cisaacstern** [comment]
@jaimergp all set. Anything else I can do here? Thanks so much for your help.

**Comment by cisaacstern** [comment]
Thanks @ocefpaf and @jaimergp!

**Pull request merged**
