### PR TITLE
Mark cuTENSOR 1.5.0 build 0 as broken

### PR DESCRIPTION
**Pull request by leofang**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata pacthes to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

Follow up of https://github.com/conda-forge/cutensor-feedstock/pull/27#discussion_r831718735. This PR marks the accidentally uploaded, WIP packages as broken. The new packages will be generated and uploaded shortly from https://github.com/conda-forge/cutensor-feedstock/pull/27.

cc: @conda-forge/cutensor

### CODE REVIEW

**Comment by leofang** [comment]
@jakirkham @conda-forge/core we need a little help here: The broken packages still have the main tag un-removed, so it confuses the conda solver...
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=479337&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=76

**Comment by jakirkham** [comment]
I don't think the `main` label is relevant here.

The way this works is we patch the repodata to exclude broken package ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/commit/549040f96c1a61448e15b147790fed322bbd06ef ). However the build for the new repodata package [failed]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=479001&view=logs&jobId=516f237f-98f1-50a4-0946-c43fe5437b81 ). So we never got a new repodata package with these packages excluded.

Not sure why the repodata package build failed, but it appears there were a couple failing builds within the last 24hrs. Relevant snippet from the build log (in case anyone has ideas 🙂):

```python
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1647997969344/work/gen_patch_json.py", line 1720, in <module>
    sys.exit(main())
  File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1647997969344/work/gen_patch_json.py", line 1705, in main
    new_index = _gen_new_index(repodatas[subdir], subdir)
  File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1647997969344/work/gen_patch_json.py", line 435, in _gen_new_index
    indexes[index_key] = _gen_new_index_per_key(repodata, subdir, index_key)
  File "/home/conda/feedstock_root/build_artifacts/conda-forge-repodata-patches_1647997969344/work/gen_patch_json.py", line 469, in _gen_new_index_per_key
    depends.append(python_vc_deps[record['version'][:3]])
KeyError: '3.8'
```

**Comment by leofang** [comment]
Thanks John. Would it help if we kick off the repodata rebuild manually?

**Comment by jakirkham** [comment]
Given there were already a few failures before that one, no think the underlying issue will need to be resolved.

**Comment by jakirkham** [comment]
Should be addressed by PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/240 ), but it may take a bit for packages to be built, uploaded, and mirrored. Would give it ~1hr.

**Comment by leofang** [comment]
Thanks, John!

**Comment by jakirkham** [comment]
Guessing that means things are working now? 🙂

**Pull request merged**
