### PR TITLE
Mark builds of xeus_octave that do not pin octave as broken

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Cf https://github.com/conda-forge/xeus_octave-feedstock/issues/6

### CODE REVIEW

**Comment by isuruf** [comment]
I think, we'd prefer a repodata-patch instead of marking them broken.

**Comment by SylvainCorlay** [comment]
We could do that, although they are also named `xeus_octave` instead of `xeus-octave`. This is merely version 0.0.2 so this should not be too much of an issue.

**Comment by isuruf** [comment]
Quoting from the PR guidelines

> We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock)) instead of marking packages as broken. This alternative workflow makes environments more reproducible.

So, let's follow our own guidelines.

**Comment by SylvainCorlay** [comment]
Another reason why this is really broken is that we did not have [that patch](https://github.com/conda-forge/xeus_octave-feedstock/blob/main/recipe/no-fltk.patch) while conda-forge's octave is build `--without-fltk`.

**Comment by isuruf** [comment]
I'm trying to find a PR for that patch to find an explanation. Could you describe if the package is unusable or it's a warning or something like that?

**Comment by SylvainCorlay** [comment]
It is actually unusable.

**Review by isuruf — APPROVED** [review]

**Pull request merged**
