### PR TITLE
Reset token for pynldas2

### PR DESCRIPTION
**Pull request by cheginit**
## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by cheginit** [comment]
The token for pynldas2 package needs to be reset.

**Comment by cheginit** [comment]
@beckermr I waited for about an hour and triggered the build, but it's still not fixed. Here is the [link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=638525&view=logs&j=47084397-e614-5090-05b8-c04ebacb88b9&t=1f9ba02e-082d-514c-d988-1f2fe7ad8510) to the build.

**Comment by beckermr** [comment]
Just worked. You need a brand new job since azure doesn't pass new secrets to old jobs.

**Comment by cheginit** [comment]
Ah, I see. Makes sense. So, in these situations, I should trigger a new build using, for example, a bot rerender command, or is there a way for me to trigger a new Azure build manually?

**Comment by beckermr** [comment]
PUsh an empty commit to the branch. That's the most reliable.

**Comment by cheginit** [comment]
Great. Thanks!

**Comment by jakirkham** [comment]
Also one can click on the status of the latest commit. On that page there is a "Re-run all checks" button one can push.

Screen Shot 2023-01-09 at 4 25 39 PM

**Comment by cheginit** [comment]
@jakirkham I actually tried that one but didn't work. I think what @beckermr is saying is that in these situations, a simple rerun does not work, and a new build should be triggered.

**Comment by beckermr** [comment]
Yeah many of the buttons we click rerun the same job. An empty commit to main is the safest.

**Comment by beckermr** [comment]
You need a new pipeline instance on azure, not a rerun of an old one. I think those appear with a date and then .1 .2 etc.

**Comment by cheginit** [comment]
I see the same exact thing that you showed. I tried twice with the re-run button, but both times the build failed with the same error.

**Comment by jakirkham** [comment]
It's worth noting that the default setting of the button is to only re-run failed jobs, which won't work (as Matt said above). However there is a dropdown menu on that button that one must use to select re-run all jobs for it to work.

**Comment by cheginit** [comment]
Right, thanks.

**Pull request merged**
