### PR TITLE
Broken: noarch nose (build 1005)

### PR DESCRIPTION
**Pull request by dwhswenson**
`nose` can't be fully noarch because it generates different code for Python 2 and Python 3 (dealing with metaclasses). See details in https://github.com/conda-forge/nose-feedstock/issues/23.

New build in https://github.com/conda-forge/nose-feedstock/pull/24.

ping @conda-forge/nose

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by beckermr** [comment]
We no longer support python2, so I believe noarch is now fine.

**Comment by beckermr** [comment]
cc @mariusvniekerk

**Comment by synapticarbors** [comment]
We might want to add a restriction on `python` to `python >=3.6` just to be explicit so people don't pull it into their python2 envs.

**Comment by beckermr** [comment]
Yup @synapticarbors . I made a comment on conda-forge/nose-feedstock#24.

**Comment by jakirkham** [comment]
xrefing this comment too ( https://github.com/conda-forge/nose-feedstock/pull/24#issuecomment-706415893 )

**Pull request merged**
