### PR TITLE
Remove broken kedro-pack-1.0.0

### PR DESCRIPTION
**Pull request by millsks**
## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by millsks** [comment]
ping @conda-forge/kedro-pack please review.

**Comment by beckermr** [comment]
What is broken here? I don't see a description.

**Comment by millsks** [comment]
Hi Matthew. This version is missing the actual source that is goes along with it.  The version ingredient also changed so to get the correct version someone would have to specify kedro-pack==0.18.12.1 because the newer version is lower than the 1.0.x.  It would choose the wrong version every time.

**Comment by beckermr** [comment]
thank you!

**Comment by millsks** [comment]
Thanks @beckermr!  What is the normal turn around where we would see this version removed from conda-forge?

**Comment by beckermr** [comment]
in the next 20-40 minutes or so - the repodata patches rebuild and then a cdn sync happens

**Pull request merged**
