### PR TITLE
Archive `theano`

### PR DESCRIPTION
**Pull request by jakirkham**
As `theano` is no longer maintained and has been superseded by `aesara`, this archives `theano`.

xref: https://github.com/conda-forge/theano-feedstock/issues/39

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [x] I want to archive a feedstock:
  * [x] Pinged the team for that feedstock for their input.
  * [x] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [x] Linked that issue in this PR description.
  * [x] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/theano

**Comment by jakirkham** [comment]
Seeing the following error [on CI]( https://github.com/conda-forge/admin-requests/actions/runs/3845518611/jobs/6549753457 )

```python
Archiving conda-forge/theano-feedstock...
Traceback (most recent call last):
  File "archive_feedstock.py", line 71, in <module>
    main(owner="conda-forge", check_only=check_only)
  File "archive_feedstock.py", line 59, in main
    archive_repo(owner, f"{feedstock}-feedstock", archive=True, check_only=check_only)
  File "archive_feedstock.py", line 19, in archive_repo
    "Authorization": f"***'GITHUB_TOKEN']}",
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'GITHUB_TOKEN'
Error: Process completed with exit code 1.
```

cc @jaimergp

**Comment by jakirkham** [comment]
Should we be [using a token]( https://github.com/conda-forge/admin-requests/blob/a45887c5a44429aeb0e14aae991a2dc4371063cd/.github/workflows/master.yml#L100-L101 ) for archiving in PRs as well?

cc @beckermr

**Comment by jaimergp** [comment]
I'll open a PR to fix this. The PR CI should only test whether the feedstock can be archived because (a) it exists and (b) it is not archived. I forgot to export the `GITHUB_TOKEN` env var from `secrets.GITHUB_TOKEN`. This token only has read permissions on PRs, IIRC.

**Comment by jaimergp** [comment]
Turns out that part of the API is public, so no token needed. Check https://github.com/conda-forge/admin-requests/pull/537

**Comment by jakirkham** [comment]
Powercycling to refresh CI

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
Let's take this for a spin 😄

**Comment by jakirkham** [comment]
Seems to have worked as expected! 🎉

**Comment by jakirkham** [comment]
It looks like the file archiving this feedstock is [not getting removed]( https://github.com/conda-forge/admin-requests/blob/57b5b69d3d93283e63409696839ba2467ffb38f2/archive/theano.txt ). As a result, we still try to archive the feedstock after it is done resulting in [a CI failure]( https://github.com/conda-forge/admin-requests/actions/runs/3851513604/jobs/6562769078#step:10:15 ). Think we need to do something similar to marking packages broken (or unbroken) where [we remove these files on completion]( https://github.com/conda-forge/admin-requests/blob/57b5b69d3d93283e63409696839ba2467ffb38f2/mark_broken.py#L81-L84 ). Pushing changes should [already be handled for us]( https://github.com/conda-forge/admin-requests/blob/73a1819b26e95cddf613485894dfdb0aede6be73/.github/workflows/master.yml#L103 ) (unless I'm missing something)

**Pull request merged**
