### PR TITLE
Archive thrust and cub feedstocks

### PR DESCRIPTION
**Pull request by kkraus14**
## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [x] I want to archive a feedstock:
  * [x] Pinged the team for that feedstock for their input.
  * [x] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [x] Linked that issue in this PR description.
  * [x] Added links to any other relevant issues/PRs in the PR description.

Once the cuda-cccl recipe is merged (https://github.com/conda-forge/staged-recipes/pull/21953) there is agreement across all maintainers that we should archive the thrust and cub feedstocks. Please see the issue here for agreement: https://github.com/conda-forge/thrust-feedstock/issues/19.

For additional context: CCCL contains thrust, cub, and libcudacxx and it has been communicated by the CCCL team at NVIDIA that they intend to further blend the three over time where it doesn't make sense to keep them separated.

<hr>

Fixes https://github.com/conda-forge/thrust-feedstock/issues/19
Fixes https://github.com/conda-forge/cub-feedstock/issues/24

### CODE REVIEW

**Comment by leofang** [comment]
cc: @conda-forge/thrust & @conda-forge/cub for vis

**Review by leofang — APPROVED** [review]

**Comment by jakirkham** [comment]
Noted issues to close in the OP

**Comment by jakirkham** [comment]
cc @adibbley @bdice @robertmaynard (for awareness)

**Comment by jakirkham** [comment]
Thanks Keith for the PR and Leo for the review! 🙏

**Comment by leofang** [comment]
btw I pinned both issues in the respective feedstocks to make it clear.

**Comment by leofang** [comment]
(got it done right before they got archived!)

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

FWIW we can unarchive using the same process. So if we need to make other small changes, there's a way to do that.

**Pull request merged**
