### PR TITLE
Marked conda-build 3.28 as broken

### PR DESCRIPTION
**Pull request by JohanMabille**
conda-build 3.28 now requires `package/version` to be found in the meta.yaml, see [this diff](https://github.com/conda/conda-build/compare/3.27.0...3.28.0#diff-cf6e2d8905542a0e7aac26cae115f65b848dd3498b72a43051f0a8900de2c13cL684-R686) (If that link doesn't open to the right lines: Files Changed -> search "package/version").

However, this was not required for split packages before, and thus this change is potentially breaking a lot of feedstocks (it is breaking [mamba-feedstock](https://github.com/conda-forge/mamba-feedstock/pull/204) for instance).

### CODE REVIEW

**Review by SylvainCorlay — APPROVED** [review]

**Comment by jezdez** [comment]
Le sigh, just wanted to mention that we've seen this and work on a fix..

**Comment by mbargull** [comment]
FWIW, a local build (with slightly different set of packages, but including `conda-build=3.28`) of https://github.com/conda-forge/mamba-feedstock/pull/204/commits/eabfae27f24c16bb4a97c79c729c8ca47ea3055c (with all scripts replaced by calls to `true`) did not trigger the issue for me. :shrug:

**Comment by mbargull** [comment]
Upstream is working on fixing the issue -- so let's wait for that until we use `conda-build>=3.28.0` in production on conda-forge.
As always, thanks everyone for looking into this!

**Review by mbargull — APPROVED** [review]

**Comment by wolfv** [comment]
I guess this is also something new from the last release? https://github.com/mamba-org/boa/issues/388

**Comment by jezdez** [comment]
> I guess this is also something new from the last release? [mamba-org/boa#388](https://github.com/mamba-org/boa/issues/388)

I don't think it's the same issue, this sounds like a possible _other_ issue related how metadata is used. I wasn't aware that boa is passing around their own classes.

**Pull request merged**
