### PR TITLE
Make featuretools-1.0.0rc1 as broken

### PR DESCRIPTION
**Pull request by gsheni**
- We released Featuretools 1.0.0rc1 in the main channel instead of using the rc label by mistake.
- See: https://github.com/conda-forge/featuretools-feedstock/pull/80

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

ping @conda-forge/featuretools

### CODE REVIEW

**Comment by gsheni** [comment]
@conda-forge/core Should I merge in the feedstock [MR](https://github.com/conda-forge/featuretools-feedstock/pull/80) first or this MR?

**Comment by beckermr** [comment]
The order doesn't matter. There is going to be a few hour delay before things change on the index anyways.

**Comment by gsheni** [comment]
@beckermr Should the build number change for the `rc` label on the feedstock? 
- https://github.com/conda-forge/featuretools-feedstock/pull/81

**Comment by gsheni** [comment]
> yes

@beckermr should the build numbers be reset to 0 or incremented from the broken build number (2 -> 3) or put as 1 (assuming it was [changed](https://github.com/conda-forge/featuretools-feedstock/commit/185b196413e0f7827001ca975f45d5fe5b5c3866#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR15) to 0 in the broken build)?

**Comment by beckermr** [comment]
At the same version increment

**Comment by gsheni** [comment]
Gotcha, thanks for all the help!

**Pull request merged**
