### PR TITLE
Remove alpha packages for jupyter-sysml-kernel

### PR DESCRIPTION
**Pull request by ivan-gomes**
Kindly requesting removal of alpha (only used for internally testing; has not been distributed/publicized) packages of jupyter-sysml-kernel - ref: https://github.com/conda-forge/jupyter-sysml-kernel-feedstock. These alpha packages were unfortunately published with calendar versioning, e.g. `2021.05a`. This has been corrected with the first non-alpha being published as `0.14.1`, but because of semver rules `2021.05a` still shows up as the latest and default version for the package which is problematic for installing users.

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [X] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [X] Added a description of the problem with the package in the PR description.
* [X] Added links to any relevant issues/PRs in the PR description.
* [X] Pinged the team for the package for their input.

ping @conda-forge/jupyter-sysml-kernel 

P.S. I am the primary maintainer of this recipe.

### CODE REVIEW

**Comment by isuruf** [comment]
I don't understand. Latest release https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases seems to be calver.

**Comment by ivan-gomes** [comment]
> I don't understand. Latest release https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases seems to be calver.

Thanks for looking into it @isuruf, much appreciated! We do use calver for Git tags, but all of our packages/artifacts are semver, ex. https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/packages/597995 and https://www.npmjs.com/package/@systems-modeling/jupyterlab-sysml. It seems that semver has the least friction across package/artifact repositories, so we're standardizing on it.

**Comment by ivan-gomes** [comment]
Ping @conda-forge/core and thanks in advance. Don't mean to bug, but we are hoping to have this resolved so it can be included in public communication.

**Comment by ivan-gomes** [comment]
@conda-forge/core, could you kindly help us with this? Our next release window is this coming week and resolution of this issue is necessary to include conda-forge in it. 

@isuruf hope you don't mind me tagging you as well.

**Comment by xhochy** [comment]
Thanks for the link to `npm` that was the only other source to the versioning. You should definitely document the versioning in the main repository.

**Pull request merged**
