### PR TITLE
Reset tokens of feedstocks that failed uploads

### PR DESCRIPTION
**Pull request by jakirkham**
Using [this search]( https://github.com/search?q=org%3Aconda-forge+is%3Aissue+is%3Aopen+created%3A%3E%3D2023-01-01++%22invalid+feedstock+token%22+&type=issues&s=created&o=desc ), all of these feedstocks had failed uploads recently. This resets all of their tokens.

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by jakirkham** [comment]
@beckermr, could you please let me know what you think of this?

**Comment by beckermr** [comment]
Some of these are dupes but why not.

**Comment by aschonfeld** [comment]
Thanks!

**Comment by beckermr** [comment]
wait until the job on main finishes before retrying builds

**Comment by aschonfeld** [comment]
How do you check the jobs running?

**Comment by beckermr** [comment]
Check the run action on this repo. I had to cancel it to make a small change for efficiency.

**Comment by beckermr** [comment]
It takes about 20-30 seconds per feedstock so this PR will take roughly 30-40 minutes to go through.

**Comment by beckermr** [comment]
This job here: https://github.com/conda-forge/admin-requests/actions/runs/3897392191/jobs/6655024135

**Comment by aschonfeld** [comment]
Thanks Matt

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Sorry tried dedup some, but it's tricky to do well 😅

**Comment by jakirkham** [comment]
Looks like these completed in [this GHA job]( https://github.com/conda-forge/admin-requests/actions/runs/3897566343/jobs/6655376643#step:9:1 )

**Comment by jakirkham** [comment]
Went through and restarted CI for all of these. If I missed any, please feel free to grab them.

Found a few more that need resets that were missed before or very recently had issues. Handling them in PR ( https://github.com/conda-forge/admin-requests/pull/642 )

**Pull request merged**
