### PR TITLE
libcpucycles token reset (pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/libcpucycles-feedstock/issues/1

This failed to generate a new token previously. This tries again.

cc @matthiasdiener @beckermr

xref: https://github.com/conda-forge/libcpucycles-feedstock/issues/1#issuecomment-1374490221
xref: https://github.com/conda-forge/admin-requests/pull/541

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by beckermr** [comment]
The job retries itself on main so no need for new PRs.

**Comment by jakirkham** [comment]
Is that new logic? In any event, it appeared to have been removed even though the job failed.

**Comment by beckermr** [comment]
Can you send me the ci run?

**Comment by jakirkham** [comment]
The 2nd reset seems to have done the right thing. So not sure if it is worth further investigation

**Comment by beckermr** [comment]
I'd like to figure it out. One thing that can happen is that if you start the CI job too soon, it can appear to not work.

**Comment by jakirkham** [comment]
Ok though I think you may know more than me here ( https://github.com/conda-forge/libcpucycles-feedstock/issues/1#issuecomment-1374490221 )

**Comment by beckermr** [comment]
Ahhhhh. Yeah I removed GHA and removed the archive files that caused a bug in Jaime's stuff. That one did fail but for unrelated reasons. All good!

**Comment by jakirkham** [comment]
Ok so this may have been duplicative then. Just wanted to make sure this one wasn't left hanging

**Pull request merged**
