### PR TITLE
Mark latest pip as broken

### PR DESCRIPTION
**Pull request by isuruf**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [ ] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label)
* [ ] Added a description of the problem with the package in the PR description.
* [ ] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by isuruf** [comment]
Ref: https://github.com/conda-forge/pip-feedstock/issues/58

cc @conda-forge/pip

**Comment by CJ-Wright** [comment]
any idea why it's breaking?

**Comment by isuruf** [comment]
No idea.

**Comment by CJ-Wright** [comment]
It looks like it isn't even getting the old pip filepath right, since that should be noarch as well

**Comment by mbargull** [comment]
@isuruf, I don't know what's up with it, but I'd assume it's something system-related?
You could rebuild the container image (i.e., doing the `conda`/`pip` updates upfront).

**Comment by isuruf** [comment]
Rebuilding the docker image fixed things. Thanks

**Comment by isuruf** [comment]
I also restarted the dozen or so PRs failing due to this issue.

**Pull request closed without merging**
