### PR TITLE
Create `token_reset/sccache.txt`

### PR DESCRIPTION
**Pull request by ajschmidt8**
## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
This PR is a follow-up to:

- https://github.com/conda-forge/admin-requests/pull/837
- https://github.com/conda-forge/admin-requests/pull/838

**Comment by ajschmidt8** [comment]
@ocefpaf, thanks for merging. do you know why the token reset fails for Travis?

see these latest automated commits to `main`:

- https://github.com/conda-forge/admin-requests/commit/1ecdd996c5fa6bcb51ccd14dfc296f8ffe3fc365
- https://github.com/conda-forge/admin-requests/commit/c1e7950abe2d71cfa71ac110386e4ea2379d1c78
- https://github.com/conda-forge/admin-requests/commit/072786d6f80ff1bb7c1b80b87202ee7976a03900

**Comment by ocefpaf** [comment]
Nope but you can try the no Travis option. Not sure if that is documented (I'm on mobile only to check) but you can find examples in the past PRs merged here.

**Comment by jakirkham** [comment]
Yeah skipping Travis would be easier

Unfortunately it doesn't sound like an option in this case

Relevant past discussion: https://github.com/conda-forge/admin-requests/pull/838#issuecomment-1748021112

**Comment by ajschmidt8** [comment]
We need the Travis token to build arm variants of the sccache feedstock.

Is there no one who can troubleshoot this problem?

I would assume this problem will affect all Travis tokens across conda-forge which seems like a pretty big problem.

The alternative of configuring every feedstock to do cross-compilation for arm variants seems like a lot more effort than just fixing the Travis token issue.

**Pull request merged**
