### PR TITLE
Mark libxml2 2.9.12 as unbroken again

### PR DESCRIPTION
**Pull request by basnijholt**
See discussion here https://gitter.im/conda-forge/conda-forge.github.io?at=63868ed5bcdb0060b8447ee8.

It turns out that the https://github.com/conda-forge/admin-requests/pull/514 PR should not have been merged. The build was not broken, there was [just a bug](https://gitlab.gnome.org/GNOME/libxml2/-/issues/255) in the libxml2 package. This package was marked as broken because of the issues described in https://github.com/conda-forge/lxml-feedstock/issues/75.

Ref: https://github.com/conda-forge/libxml2-feedstock/issues/80

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/libxml2

**Review by ocefpaf — APPROVED** [review]
@basnijholt this looks good to go. Let's wait for @beckermr to see if he wants to send the repodatapatch before we merge this or not.

**Comment by beckermr** [comment]
I won't get to this for a while. Do what you need to.

**Comment by ocefpaf** [comment]
> I won't get to this for a while. Do what you need to.

I'll send this back to @basnijholt. How broken is your workflow without this? Very, merge right away! Or nah, we can wait.

**Comment by basnijholt** [comment]
Our workflow is pretty broken because of this unfortunately. We cannot create a new environment because dependencies cannot be resolved.

**Comment by hmaarrfk** [comment]
> Our workflow is pretty broken because of this unfortunately. We cannot create a new environment because dependencies cannot be resolved.

We attempted to make any package that was built with libxml 2.9 as compatible with 2.10.

I'm wondering if this didn't get catch a package you needed:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/339


Can you share how you construct your environment?

**Comment by tdejager** [comment]
> > Our workflow is pretty broken because of this unfortunately. We cannot create a new environment because dependencies cannot be resolved.
> 
> We attempted to make any package that was built with libxml 2.9 as compatible with 2.10.
> 
> I'm wondering if this didn't get catch a package you needed: [conda-forge/conda-forge-repodata-patches-feedstock#339](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/339)
> 
> Can you share how you construct your environment?

See https://github.com/RoboStack/ros-noetic/issues/310 for an example

**Comment by wolfv** [comment]
We have problems with this patch in robostack as well -- where we cannot apply repodata patches.

**Pull request merged**
