### PR TITLE
Mark broken protobuf packages with incorrect version numbers

### PR DESCRIPTION
**Pull request by xylar**
Because of confusion about protobuf's version numbering scheme
and the way the bot detected it, 2 package versions were introduced
with incorrect version numbers (3.21.1 and 21.2, repsectively).
These should have been 4.21.1 and 4.21.2, respectively.

Relevant discussion is here:
https://github.com/conda-forge/protobuf-feedstock/pull/147
and here:
https://github.com/conda-forge/protobuf-feedstock/pull/146#issuecomment-1149410254

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge/protobuf, flagging you to make you aware of this.

@tpdownes, also flagging you.  Thank you for your kindness and patience in explaining the problem.  It took me awhile to get it but I'm onboard now and will ask for your approval as I attempt to fix this.

**Comment by h-vetinari** [comment]
> 2 package versions were introduced
> with incorrect version numbers (3.21.1 and 21.2, repsectively).

I would have though 3.21 is alright as it's still following the old naming scheme?



> These should have been 4.21.1 and 4.21.2, respectively.

Afaict, libprotobuf itself should stay at 3.x, and only the python bindings get 4.x

**Comment by h-vetinari** [comment]
> > These should have been 4.21.1 and 4.21.2, respectively.
> 
> Afaict, libprotobuf itself should stay at 3.x, and only the python bindings get 4.x

NVM, this PR just did protobuf anyway, not libprotobuf. We also need to mark libprotobuf 21.x as broken (but not 3.21.1).

**Comment by xylar** [comment]
@h-vetinari, you have that exactly right.  But `libprotobuf` has moved erroneously to 21.x instead of 3.21.x and that need to be fixed as well.

**Comment by xylar** [comment]
@h-vetinari, yes, what you said!

**Comment by xylar** [comment]
Thanks @ocefpaf!!!

**Comment by xylar** [comment]
This helps to assuage some of my guilt at rushing in and messing things up.  Better luck tomorrow...

**Pull request merged**
