### PR TITLE
Mark arch versions of `allure-*` packages as broken

### PR DESCRIPTION
**Pull request by kenodegard**
The initial implementation of the allure-python-feedstock (for the `allure-*` packages) mistakenly built for all archs (instead of being noarch), see https://github.com/conda-forge/allure-python-feedstock/pull/2.

This "removes" these redundant packages.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

Xref https://github.com/conda-forge/allure-python-feedstock/pull/2
Cc @conda-forge/allure-python

### CODE REVIEW

**Comment by jakirkham** [comment]
So these packages are not actually broken right? Just extra?

If so, think we can leave them there

**Comment by nsoranzo** [comment]
I'm just worried conda may prefer older platform-specific packages to newer noarch ones, but if that's not the case I suppose this is not needed.

**Comment by ocefpaf** [comment]
> I'm just worried conda may prefer older platform-specific packages to newer noarch ones.

I never ran solver experiments to check this but, in theory, the solvers based on libmamba always prioritize higher build numbers. If the noarch are newer, they'll be preferred.

**Comment by kenodegard** [comment]
Ok I'll close this for now, can always reopen if we find that these arch packages cause issues later

**Pull request closed without merging**
