### PR TITLE
Mark libpq and postgresql 16.1 builds 1 2 and 4 as broken due to openssl 3.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
See discussion https://github.com/conda-forge/postgresql-feedstock/issues/191

cc: @h-vetinari @akrherz 

These packages were built requiring "openssl>=3.2", but with that version of openssl, users experience errors at runtime because we forgot to merge in a patch

the fix is proposed: https://github.com/conda-forge/postgresql-feedstock/pull/192/files

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

* [ ] I want to request (or revoke) access to an opt-in CI resource:
  * [ ] Pinged the relevant feedstock team(s)
  * [ ] Added a small description explaining why access is needed

### CODE REVIEW

**Comment by hmaarrfk** [comment]
cc: @conda-forge/postgresql

**Review by akrherz — APPROVED** [review]
Thank you

**Comment by h-vetinari** [comment]
I think we need to mark all dependent builds from the same run as broken too. E.g. `postgresql` depends exactly on `libpq` and so those builds would run into weird resolver errors. Same for `postgresql-python`

**Comment by hmaarrfk** [comment]
Ok thanks for the suggestion this is indeed a good idea.

**Pull request merged**
