### PR TITLE
Reset token for r-forge

### PR DESCRIPTION
**Pull request by mbargull**
Copying from cf-staging fails due to "invalid feedstock token".
refs:
- https://github.com/conda-forge/r-forge-feedstock/issues/8

cc @conda-forge/r-forge

----

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by mbargull** [comment]
Thanks for the merge!
But apparently there's something going on with Travis:
The last runs of https://github.com/conda-forge/admin-requests/actions/workflows/master.yml all show:
```
RuntimeError: Failed to register feedstock token for conda-forge/r-forge-feedstock on travis!
failed to reset token for 'r-forge': CalledProcessError(1, ['conda', 'smithy', 'register-feedstock-token', '--without-circle', '--without-drone', '--feedstock_directory', '/tmp/tmp1m5yxkun/r-forge-feedstock', '--organization', 'conda-forge', '--token_repo', 'https://x-access-token:${GITHUB_TOKEN}@github.com/conda-forge/feedstock-tokens'])
```

**Comment by beckermr** [comment]
We are likely out of requests. Retry the workflow later. This workflow uses the same tokens and code as staged recipes.

**Comment by dpryan79** [comment]
We're still running into invalid feedstock token errors.

**Comment by beckermr** [comment]
Does a retry fix it ?

**Comment by dpryan79** [comment]
I've retried the upload jobs from the master branch already without success. Should I try rerendering as well?

**Comment by dpryan79** [comment]
Rerendering doesn't seem to update anything in this case.

**Comment by beckermr** [comment]
Which feedstocks?

**Comment by dpryan79** [comment]
Just r-forge that I've seen so far: https://github.com/conda-forge/r-forge-feedstock

**Comment by beckermr** [comment]
Ah ok. Looks like Travis is still barfing on the token reset.

**Comment by beckermr** [comment]
I'll have to debug locally but won't get a chance for a while. Is this a big blocker?

**Comment by dpryan79** [comment]
Not a big one, no. It's only blocking a handful of packages in the R 4.2 migration, so it doesn't really matter if this gets addressed today or next week. Thanks!

**Comment by mbargull** [comment]
Apart from the remaining `r-v8` subgraph (about 40 feedstocks), this is now the "biggest" blocker with (if I counted correctly) 6 downstream feedstocks. So, yeah, not many -- but depending on how fast we can handle the `r-v8` stuff, this could get to a "tail end of the R 4.2 migration" status ;).

----
All workflow runs of https://github.com/conda-forge/admin-requests/actions failed since merging this PR with token registration on Travis not working (see https://github.com/conda-forge/admin-requests/pull/496#issuecomment-1275987975 ).
OTOH, registering token for new feedstocks seem to work no problem: https://github.com/conda-forge/staged-recipes/actions/workflows/create_feedstocks.yml

So might be rather specific to https://github.com/conda-forge/r-forge ? (Not sure if relevant/if it helps to pin point the issue: that feedstock also hasn't been built since the CFEP13 token cleanup migration.)

**Comment by beckermr** [comment]
Travis appears to not have this feedstock on its website - https://app.travis-ci.com/github/conda-forge/r-forge-feedstock

IDK why. Maybe we can submit it to staged recipes again to see if that helps?

**Comment by beckermr** [comment]
Or we could disable Travis here...

**Comment by mbargull** [comment]
Thanks for looking into it!
Since the feedstock doesn't use Travis anyway, disabling it would be more than enough :).

**Comment by beckermr** [comment]
Right ok. We'll have to make a special run of the feedstock token reset code or add that feature. I will try for today.

**Comment by mbargull** [comment]
Thank you! Just started it and will check in 4-5 hours (afk).

**Comment by dpryan79** [comment]
Seems to have done the trick!

**Pull request merged**
