### PR TITLE
Create request for xlarge runner

### PR DESCRIPTION
**Pull request by carterbox**
## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

* [x] I want to request (or revoke) access to an opt-in CI resource:
  * [x] Pinged the relevant feedstock team(s)
  * [x] Added a small description explaining why access is needed

* [ ] I want to copy an artifact following [CFEP-3](https://github.com/conda-forge/cfep/blob/main/cfep-03.md):
  * [ ] Pinged the relevant feedstock team(s)
  * [ ] Added a reference to the original PR
  * [ ] Posted a link to the conda artifacts
  * [ ] Posted a link to the build logs

We are trying to build flash-attn. [Our current prototype builds take 28 hours with `MAX_JOBS=1`.](https://github.com/conda-forge/flash-attn-feedstock/pull/10#issuecomment-2272623712) Increasing the number of compiler jobs causes the large size runner to crash. We want to try more compiler jobs on a runner with more RAM in order to reduce the build time.

### CODE REVIEW

**Review by jaimergp — APPROVED** [review]

**Comment by carterbox** [comment]
Thanks, @jaimergp

**Comment by carterbox** [comment]
@jaimergp, this PR failed to run post-merge.

https://github.com/conda-forge/admin-requests/actions/runs/10595219469/job/29360497628

**Comment by jakirkham** [comment]
> ...this PR failed to run post-merge.
> 
> https://github.com/conda-forge/admin-requests/actions/runs/10595219469/job/29360497628

Snippet of the traceback below:

```python
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/cf/lib/python3.10/site-packages/conda_build/metadata.py", line 2010, in _get_contents
    rendered = template.render(environment=env)
  File "/home/runner/miniconda3/envs/cf/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/runner/miniconda3/envs/cf/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/tmp/tmplr3f7tv4/flash-attn-feedstock/recipe/meta.yaml", line 37, in top-level template code
    - {{ compiler('cuda') }}
jinja2.exceptions.UndefinedError: 'cuda_compiler_version' is undefined
```

The recipe correctly [`skip`s cases where `cuda_compiler_version` is `undefined`]( https://github.com/conda-forge/flash-attn-feedstock/blob/ea58e7d80215a9ed2788a0555e21d877c2c7bcc4/recipe/meta.yaml#L22 )

Think this goes back to a `conda-build` bug that was fixed in 24.9.0 with PR ( https://github.com/conda/conda-build/pull/5458 ) and subsequently released in conda-forge ( https://github.com/conda-forge/conda-build-feedstock/pull/230 )

Looks like this request was skipped while it was broken ( https://github.com/conda-forge/admin-requests/commit/b447fae8cea5e712b8fb05e92012334484481d71 ). Since the conda-build issue has since been fixed, retrying with PR ( https://github.com/conda-forge/admin-requests/pull/1101 )

**Comment by jakirkham** [comment]
That fixed it: https://github.com/conda-forge/admin-requests/pull/1101#issuecomment-2400794329

**Pull request merged**
