### PR TITLE
Create orekit.txt file for resetting CircleCI toke

### PR DESCRIPTION
**Pull request by petrushy**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [ ] Added a description of the problem with the package in the PR description.
* [ ] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by petrushy** [comment]
Hi,

I am having issues with this PR:
https://github.com/conda-forge/orekit-feedstock/pull/64

"CircleCI Pipeline — Could not find a usable config.yml, you may have revoked the CircleCI OAuth app."

**Comment by beckermr** [comment]
We've deprecated circle. Please try switching to azure first.

**Comment by jakirkham** [comment]
Right it looks like the user has already dropped CircleCI in that PR, but it is giving odd error messages. Is there any harm in merging this?

**Comment by beckermr** [comment]
Ahhhhh I see. Let me go to the feedstock and delete the webhook by hand. If that works we can close this.

**Comment by jakirkham** [comment]
Sounds good. Thanks Matt! 🙏

**Comment by beckermr** [comment]
OK. This will work for future PRs. you may still see a failed check for the current one. It can be ignore.

**Comment by beckermr** [comment]
I am going to close this PR for now. If you are having issues in future PRs, feel free to reopen.

**Comment by BastianZim** [comment]
I've seen this in roughly 50 of my feedstocks. Do they all need to be deleted by hand or is there something I can do?

**Comment by beckermr** [comment]
We can use the admin migrations repo to remove the hooks everywhere if we want.

**Pull request closed without merging**
