### PR TITLE
Remove broken `bw2calc` (label `dev`) Packages

### PR DESCRIPTION
**Pull request by michaelweinold**
## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

## Description

The `dev` versions of [`bw2calc`](https://github.com/brightway-lca/brightway2-calc) were added to the conda-forge channel under the `dev` label. Unfortunately, the package was not released as `noarch`. This complicates downstream development efforts depending on this package. Related discussions in these PRs:

- https://github.com/conda-forge/bw2calc-feedstock/pull/14
- https://github.com/emscripten-forge/recipes/pull/616

The platform specific `dev` versions (cf. the `broken/bw2calc_broken.txt` file) should be removed entirely. They are to be replaced with a `noarch` version.

🔔 @conda-forge/bw2calc

### CODE REVIEW

**Comment by michaelweinold** [comment]
@conda-forge/core, this is ready for review. Not sure why the checks are failing. I formatted the file exactly like eg. https://github.com/conda-forge/admin-requests/pull/686/files, where the checks are passing.

**Comment by ocefpaf** [comment]
I wonder if it is the fact that those are in the dev label that is causing this error. I'm not sure our automated labeling system covers that case.

**Comment by michaelweinold** [comment]
> Also, the channel should not be used in general but artefacts should use their own <name>_dev channel for development releases. Otherwise, an enduser cannot select from which artefact they want to try out dev releases.

Are you saying we should have created a branch `bw2calc_dev` instead of `dev` in the `bw2calc` repo?

We successfully installed the package by specifying the channel+label in the package specs of the usual environment files:

```
- https://conda.anaconda.org/conda-forge/label/bw2calc_dev::bw2calc=2.0.dev14
```

Maybe I'm not following - in any case, we tried to follow [CFEP-05](https://github.com/conda-forge/cfep/blob/main/cfep-05.md) to the letter.

**Comment by h-vetinari** [comment]
Yes, the automation here only works for `main`. For marking things in different labels as broken it needs someone from core (and in the cf-org on https://anaconda.org/conda-forge) to mark them broken by hand.

**Comment by h-vetinari** [comment]
The label is [already](https://anaconda.org/conda-forge/bw2calc/files) `bw2calc_dev`, as it should be.

> Unfortunately, the package was not released as `noarch`. This complicates downstream development efforts depending on this package.

Now that you have a noarch build (`2.0.dev14`), why do you still need to mark `2.0.dev13` as broken? The solver should already pull in the newer one.

**Pull request closed without merging**
