### PR TITLE
Label `arpack` v3.8.0=*_0 and =*_100 as broken

### PR DESCRIPTION
**Pull request by mrakitin**
Per https://github.com/conda-forge/arpack-feedstock/pull/47#issuecomment-1247538671.

Produced with this one-liner:
```bash
$ curl https://anaconda.org/conda-forge/arpack/files 2>&1 | grep '3\.8\.0/download' | awk -F['><'] '{print $3}' | sort -u > arpack.txt
```

---

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by mrakitin** [comment]
Thank you for your help, @beckermr Matthew!

Just curious, are the labels added via the GHA workflows in this repo, or is there a separate bot? I don't see the label set in https://github.com/conda-forge/admin-requests/actions/runs/3058630006/jobs/4935056195, maybe it's elsewhere.

**Comment by mrakitin** [comment]
I noticed the `broken` label was added:
image

Should the `main` label still be there?

**Comment by mrakitin** [comment]
I see how it's done with the GHA workflows, cool!
https://github.com/conda-forge/admin-requests/blob/246514993407ca18f33b003db0c343c87cae362a/.github/workflows/master.yml#L59-L64

Still curious about the `main` label.

**Comment by beckermr** [comment]
The main label stays on the but any package with broken is excluded from the metadata

**Comment by mrakitin** [comment]
Thanks, good to know!

**Pull request merged**
