### PR TITLE
Mark *lal*-7.1.1 builds 0-2 as broken

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Please mark *lal*-7.1.1 builds 0-2 as broken because they didn't include a necessary `run_constrained` tag, see conda-forge/lal-feedstock#50. I am the maintained of that feedstock and apologise for having borked the 7.1.1 update in the first place.

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by beckermr** [comment]
This can be fixed with a repodata patch. Why is that not the preferred solution here?

**Comment by duncanmmacleod** [comment]
> This can be fixed with a repodata patch. Why is that not the preferred solution here?

@beckermr, because I don't really know what that is and don't know how to prepare one, please advise.

**Comment by chrisburr** [comment]
@duncanmmacleod It's a way conda-forge can change the metadata of existing packages (it's preferred to minimise breakage in existing environments).

It's done modifying `recipe/gen_patch_json.py` in `conda-forge-repodata-patches-feedstock`. You can find an example of one I wrote recently for pip at: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/116/ In this case you probably want to look for the version and `record['build'].endswith(("_0", "_1", "_2", "_100", "_101", "102"))`.

**Comment by beckermr** [comment]
thanks for explaining @chrisburr!

**Pull request closed without merging**
