### PR TITLE
Remove gazebo macOS builds for which a critical regression was introduced

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/conda-forge/gazebo-feedstock/issues/161 for the discussion of the critical regression, that prevents to use gazebo on macOS at all.

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [x] I want to mark a package as broken (or not broken):
  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @conda-forge/gazebo

**Comment by traversaro** [comment]
@conda-forge/core the PR is ready for review, thanks!

**Comment by hmaarrfk** [comment]
Does build 6 work? why not just let conda/mamba find build instead of 5? The problem here is that your users won't magically get 6. I'm generally sheepish about these kinds of hotfixes (because there is always a usecase I personally tend to forget) so I like to just "release a new version and fix things there" if that works.

Sometimes it doesn't.

**Comment by beckermr** [comment]
We don’t do hot fixes for bugs in packages generally. We do allow things like this if something was yanked on pypi. That’s a special case since pypi allows this.

**Comment by traversaro** [comment]
I was aware of the bugs policy, but I tought it was a bit different in this case as with this regression (that is a packaging regression, as a patch was accidentally skipped) that is preventing to use the package at all, not just some small bug.

> Does build 6 work? why not just let conda/mamba find build instead of 5? The problem here is that your users won't magically get 6. I'm generally sheepish about these kinds of hotfixes (because there is always a usecase I personally tend to forget) so I like to just "release a new version and fix things there" if that works.

The problem is that between _2 and _6 there were two migrations (ffmpeg and libgdal), see https://github.com/RoboStack/ros-noetic/issues/323#issuecomment-1433873279. Anyhow, we can simply re-create the appropriate builds with the right pin that we need, thanks for the reply!

**Comment by hmaarrfk** [comment]
> The problem is that between _2 and _6 there were two migrations (ffmpeg and libgdal), see https://github.com/RoboStack/ros-noetic/issues/323#issuecomment-1433873279. Anyhow, we can simply re-create the appropriate builds with the right pin that we need, thanks for the reply!

I am sympathetic to this actually. I think this is would fall under a "broken" package to me.

To me, if we find that "the command `mamba install a specific combination of packages`" results in a something totally unusable, that is "broken" to me.

Usually, build number bumps fix this, but when migrations are involved, sometimes the only solution is to patch.

What do yu think @beckermr

**Comment by beckermr** [comment]
The policy is not strict and I'm no expert here. If you all think it should be merged then let's do it.

**Comment by traversaro** [comment]
Thanks @hmaarrfk !

**Pull request merged**
