### PR TITLE
token refresh for batchspawner

### PR DESCRIPTION
**Pull request by bollwyvl**
This requests a token refresh for https://github.com/conda-forge/batchspawner-feedstock/issues/6

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Please use the new yaml format for the requests.

**Comment by bollwyvl** [comment]
I wrote a [thing](https://github.com/deathbeds/jupyak/tree/main/js/demo) that builds clickable links for single-file pull requests of json/toml/yaml from JSON schema... 

https://deathbeds.github.io/jupyak/new.html

... maybe could apply that here.

**Comment by beckermr** [comment]
Oh cool! Def make an issue with the idea.

**Comment by bollwyvl** [comment]
:point_up: #968

**Comment by beckermr** [comment]
Ohhhh woops I missed that! I bet we could do this as part of the new docs repo maybe? I'm not sure how api access would work to generate a pr though. I don't want to handle credentials. 

Maybe an admin command could be interesting and easier from a security perspective?

Cc @jaimergp

**Pull request merged**
