### PR TITLE
Archive `trio_asyncio` feedstock

### PR DESCRIPTION
**Pull request by dhirschfeld**
## Checklist:

* [x] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by beckermr** [comment]
Please link to the PR on the other feedstock so we have records

**Comment by dhirschfeld** [comment]
ping @conda-forge/trio_asyncio - ar you happy for this feedstock to be archived in favour of https://github.com/conda-forge/trio-asyncio-feedstock/pull/13 which will publish packages under both `trio-asyncio` and `trio_asyncio` going forward?

**Comment by dhirschfeld** [comment]
I think Matthias isn't active on the old feedstock, but I'm happy to add him on the new one if he requests (or puts in a PR via the bot):

https://github.com/conda-forge/trio-asyncio-feedstock/pull/13#issuecomment-1655285798

**Comment by dhirschfeld** [comment]
The outputs have already been updated:
https://github.com/conda-forge/feedstock-outputs/pull/49

**Comment by dhirschfeld** [comment]
Thanks Matthew! :heart:

**Pull request merged**
