### PR TITLE
mark ffmpeg 4.4 as broken

### PR DESCRIPTION
**Pull request by h-vetinari**
See discussion [here](https://github.com/conda-forge/ffmpeg-feedstock/pull/115#issuecomment-1020619231)

### CODE REVIEW

**Comment by isuruf** [comment]
This should have been only `osx-64` and `osx-arm64`. Linux packages are fine.

**Comment by beckermr** [comment]
I can submit a pr to fix.

**Comment by beckermr** [comment]
done!

**Comment by h-vetinari** [comment]
Thanks @beckermr!

I thought that the single_module issues affected linux as well, and this matched with the "mark 4.4. as broken". Sorry for the churn.

**Pull request merged**
