### PR TITLE
Mark jupyter_client=6.1.13 as broken

### PR DESCRIPTION
**Pull request by davidbrochart**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

Need to pin python >= 3.6
Related issue: https://github.com/jupyter/jupyter_client/issues/634

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
This package seems prominent enough that a repodata patch would be better.

**Comment by davidbrochart** [comment]
But then we would have conda and PyPI out of sync, since we can't patch on PyPI?

**Comment by beckermr** [comment]
Ah you removed the pypi release?

**Comment by davidbrochart** [comment]
Not yet, but we have no choice but to yank the PyPI release.

**Comment by beckermr** [comment]
OK. yanking releases is a last resort but sometimes needed. LGTM.

**Pull request merged**
