### PR TITLE
Remove broken `pypy*` & `setuptools` packages for 3.8 & 3.9

### PR DESCRIPTION
**Pull request by jakirkham**
The `site-packages` structure was changed in these PyPy versions after these packages were produced ( https://github.com/conda-forge/pypy3.6-feedstock/pull/76 ). New `setuptools` packages are being built with the updated `site-packages` structure ( https://github.com/conda-forge/setuptools-feedstock/pull/254 ). So remove these packages the precede that change. Also remove the `pypy*` packages for 3.8 & 3.9 that preceded this change.

cc @conda-forge/pypy3-6 @conda-forge/setuptools

<hr>

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata pacthes to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [ ] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [ ] Added a description of the problem with the package in the PR description.
* [ ] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by jakirkham** [comment]
Had to go through these by hand. So would be good if someone rechecked these. Also if there are tips on how this kind of thing can be automated would be happy to learn 🙂

**Review by h-vetinari — APPROVED** [review]
Verified by cross-referencing against https://anaconda.org/conda-forge/setuptools/files

**Comment by hmaarrfk** [comment]
is it easier to simply write off all of build `_1`? I'm always worried hand checking these.

**Comment by hmaarrfk** [comment]
I'm not pro enough with jq to write the query either.

**Comment by h-vetinari** [comment]
> is it easier to simply write off all of build `_1`? I'm always worried hand checking these.

The risk is pretty negligible in this case. Aside from the fact that it was double-checked independently, we also have the correct `_2` builds that should be picked up in any case. Already marking the `_1` builds broken is an abundance of caution IMO.

**Comment by isuruf** [comment]
Can you add ppc64le `_2` builds as well? Rebuilt pypy was not uploaded at the time.

**Comment by hmaarrfk** [comment]
```
for platform in osx-arm64 win-32 osx-64 win-64 linux-64 linux-ppc64le linux-aarch64; do 
mamba repoquery search --platform ${platform} setuptools=61.2=*_1 --json | grep url | awk -F'conda-forge/' '{print $2}'  | awk -F'",' '{print $1}'
done
```

Results:
```
osx-arm64/setuptools-61.2.0-py310hbe9552e_1.tar.bz2
osx-arm64/setuptools-61.2.0-py38h10201cd_1.tar.bz2
osx-arm64/setuptools-61.2.0-py39h2804cbe_1.tar.bz2
osx-64/setuptools-61.2.0-py310h2ec42d9_1.tar.bz2
osx-64/setuptools-61.2.0-py37hf985489_1.tar.bz2
osx-64/setuptools-61.2.0-py38h25b0044_1.tar.bz2
osx-64/setuptools-61.2.0-py38h50d1736_1.tar.bz2
osx-64/setuptools-61.2.0-py39h43b90dd_1.tar.bz2
osx-64/setuptools-61.2.0-py39h6e9494a_1.tar.bz2
win-64/setuptools-61.2.0-py310h5588dad_1.tar.bz2
win-64/setuptools-61.2.0-py37h03978a9_1.tar.bz2
win-64/setuptools-61.2.0-py38h32ec214_1.tar.bz2
win-64/setuptools-61.2.0-py38haa244fe_1.tar.bz2
win-64/setuptools-61.2.0-py39h0d475fb_1.tar.bz2
win-64/setuptools-61.2.0-py39hcbf5309_1.tar.bz2
linux-64/setuptools-61.2.0-py310hff52083_1.tar.bz2
linux-64/setuptools-61.2.0-py37h89c1867_1.tar.bz2
linux-64/setuptools-61.2.0-py38h373033e_1.tar.bz2
linux-64/setuptools-61.2.0-py38h578d9bd_1.tar.bz2
linux-64/setuptools-61.2.0-py39h4162558_1.tar.bz2
linux-64/setuptools-61.2.0-py39hf3d152e_1.tar.bz2
linux-ppc64le/setuptools-61.2.0-py310hd032262_1.tar.bz2
linux-ppc64le/setuptools-61.2.0-py37h35e4cab_1.tar.bz2
linux-ppc64le/setuptools-61.2.0-py38hf1d151d_1.tar.bz2
linux-ppc64le/setuptools-61.2.0-py38hf8b3453_1.tar.bz2
linux-ppc64le/setuptools-61.2.0-py39hb881913_1.tar.bz2
linux-ppc64le/setuptools-61.2.0-py39hc1b9086_1.tar.bz2
linux-aarch64/setuptools-61.2.0-py310hbbe02a8_1.tar.bz2
linux-aarch64/setuptools-61.2.0-py37hd9ded2f_1.tar.bz2
linux-aarch64/setuptools-61.2.0-py38h2063c64_1.tar.bz2
linux-aarch64/setuptools-61.2.0-py38he37f277_1.tar.bz2
linux-aarch64/setuptools-61.2.0-py39ha65689a_1.tar.bz2
linux-aarch64/setuptools-61.2.0-py39hdc1b86f_1.tar.bz2
```

Repeat with `_2`

**Comment by h-vetinari** [comment]
I still fail to see why all `_1` need to be marked broken, but can't hurt either I guess. 🤷 
(grepping would be easier if we had https://github.com/conda/conda-build/issues/4252)

> Repeat with `_2`

I guess we'll do another setuptools rebuild (for the ppc builds that missed the boat) with `_3`...?

**Comment by hmaarrfk** [comment]
yeah, just repeat the builds.

**Comment by jakirkham** [comment]
> Can you add ppc64le `_2` builds as well? Rebuilt pypy was not uploaded at the time.

Thanks for flagging that. Missed these hadn't made it. Added those 2.

Rechecked the `aarch64` builds as well, but those seem ok.

Also submitted PR ( https://github.com/conda-forge/setuptools-feedstock/pull/255 ) to bump the build number again to get new `ppc64le` builds.

**Comment by isuruf** [comment]
Shall we mark the `pypy3.8/3.9`s `_0` builds as broken as well?

**Comment by jakirkham** [comment]
The original migration PR ( https://github.com/conda-forge/setuptools-feedstock/pull/252 ) bumped the `build/number` to `1`. There were no PyPy 3.8 or 3.9 builds for `0` (unless I'm missing something)

**Comment by isuruf** [comment]
I mean the pypy builds themselves, not setuptools builds for pypy.

**Comment by isuruf** [comment]
For eg: `linux-ppc64le/pypy3.8-7.3.8-h50729ec_0.tar.bz2`

**Comment by jakirkham** [comment]
Sorry got it. That makes more sense. Thanks for clarifying. Sure added above. PTAL 🙂

**Review by isuruf — APPROVED** [review]
Thanks @jakirkham

**Comment by hmaarrfk** [comment]
thx

**Comment by jakirkham** [comment]
Thanks for the reviews! 😀

**Pull request merged**
