### PR TITLE
ENH mark broken from travis

### PR DESCRIPTION
**Pull request by beckermr**
Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

Checklist:

* [ ] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [ ] Added a description of the problem with the package in the PR description.
* [ ] Added links to any relevant issues/PRs in the PR description.
* [ ] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/core These are packages that came from forks during the travis issues we had. Ready for review and merge!

**Comment by isuruf** [comment]
I thought we were going to make PRs before marking them broken.

**Comment by isuruf** [comment]
Can we please revert this?

**Comment by beckermr** [comment]
My plan was to make the prs later. I didn't want to delay anymore.

**Comment by beckermr** [comment]
I made a pr for this in the bot.

**Pull request merged**
