### PR TITLE
archive neworder

### PR DESCRIPTION
**Pull request by virgesmith**
see https://github.com/conda-forge/neworder-feedstock/issues/28

## Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata patches to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

## Checklist:

* [ ] I want to mark a package as broken (or not broken):
  * [ ] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [ ] Added a description of the problem with the package in the PR description.
  * [ ] Pinged the team for the package for their input.

* [ ] I want to archive a feedstock:
  * [ ] Pinged the team for that feedstock for their input.
  * [ ] Make sure you have opened an issue on the feedstock explaining why it was archived.
  * [ ] Linked that issue in this PR description.
  * [ ] Added links to any other relevant issues/PRs in the PR description.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Any rationale for archiving? (I don't see one in the other issue either)

I don't know the history of this feedstock, and I'm not against archiving of course, just curious what's up.

**Comment by jaimergp** [comment]
Looks like it's more of a project decision than anything else: https://github.com/virgesmith/neworder/issues/81 & https://github.com/conda-forge/neworder-feedstock/pull/27#issuecomment-1567108361

I don't think we should archive it just because the upstream maintainers don't want to invest energy in it (which is totally valid, don't get me wrong). @virgesmith you are free to remove yourself from the maintainers in the feedstock; maybe someone will take over. I don't know if we have a precedent for an "empty" maintainers list but worst case we can add a filler.

**Comment by ocefpaf** [comment]
> I don't know if we have a precedent for an "empty" maintainers list but worst case we can add a filler.

We don't. Usually a core members steps in for abandoned packages. I'll add myself just in case and the current maintainers can remove themselves.

**Comment by virgesmith** [comment]
Thanks @jaimergp and @ocefpaf, I've removed myself. I don't have the bandwidth to maintain conda packages (as you suspected) but it's still on pypi. I don't think there's any great need for it to continue be maintained here, but happy for you to take over if you so wish

**Pull request closed without merging**
