### PR TITLE
Remove uninstallable mpifort

### PR DESCRIPTION
**Pull request by carterbox**
This specific build of mpi-fort is uninstallable because it requires the corresponding compiler build which doesn't exist? Perhaps that build was already removed for being broken, but they forgot to remove this package too?

Guidelines for marking packages as broken:

* We prefer to patch the repo data (see [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock))
  instead of marking packages as broken. This alternative workflow makes environments more reproducible.
* Packages with requirements/metadata that are too strict but otherwise work are
  not technically broken and should not be marked as such.
* Packages with missing metadata can be marked as broken on a temporary basis
  but should be patched in the repo data and be marked unbroken later.
* In some cases where the number of users of a package is small or it is used by
  the maintainers only, we can allow packages to be marked broken more liberally.
* We (`conda-forge/core`) try to make a decision on these requests within 24 hours.

What will happen when a package is marked broken?

* Our bots will add the `broken` label to the package. The `main` label will remain on the package and this is normal.
* Our bots will rebuild our repodata pacthes to remove this package from the repodata.
* In a few hours after the `anaconda.org` CDN picks up the new patches, you will no longer be able to install the package from the `main` channel.

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

### CODE REVIEW

**Comment by carterbox** [comment]
Related to https://github.com/conda-forge/staged-recipes/pull/14726

**Comment by carterbox** [comment]
@conda-forge/openmpi

**Comment by leofang** [comment]
Thanks, @carterbox. Good catch. I should have done this in #17... Since you're at it, would you mind also removing `openmpi-mpicc` and `openmpi-mpicxx` with the same version and build numbers? I bet they don't work either.

**Comment by carterbox** [comment]
```       
openmpi-mpicc                  4.0.2      h516909a_3  conda-forge                
openmpi-mpicxx                 4.0.2      hc9558a2_3  conda-forge                
openmpi-mpifort                4.0.2      he991be0_3  conda-forge         
```
These are the package infos. Someone check that I got the tarball names right.

**Review by leofang — APPROVED** [review]

**Comment by carterbox** [comment]
There already is a newer build of these packages, but the solver chooses these old ones anyways. I don't know why.

The problem is that these packages have a pinned dependency on a build of openmpi that was already marked as broken, so they cannot be installed.

It seems better to mark these uninstallable packages as broken than to modify every recipe to avoid this specific build of these packages.

**Comment by jakirkham** [comment]
Thoughts @conda-forge/core? 🙂

**Comment by hmaarrfk** [comment]
I believe the issue is that you need to add the cuda compilers so that the recepe generates multiple build strings of mpifort
https://github.com/conda-forge/openmpi-feedstock/blob/master/recipe/meta.yaml#L99

Should look like:
```
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ compiler('cuda') }}  # [linux64]
```
That way your build matrix gets built out.

**Comment by hmaarrfk** [comment]
Hmm, nevermind. I mean honestly, probably some edge case is getting hit. I'm ok with moving on from this. But hopefully we can write some good guides to compiling with GPU support.

For one, I don't think we've documented good build string conventions and best practicies for pinning gpu/cpu.

**Comment by jakirkham** [comment]
Probably best to continue that discussion in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1059 ) (assuming this is covering the same thing)

**Comment by carterbox** [comment]
Thanks for merging.

**Comment by jakirkham** [comment]
Nor am I. Though I haven't spent any time digging into this

**Pull request merged**
