### PR TITLE
Reset several tokens

### PR DESCRIPTION
**Pull request by xylar**
## Checklist:

  * [x] Make sure your package is in the right spot (`broken/*` for adding the
    `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
    for token resets)
  * [x] Added a description of the problem with the package in the PR description.
  * [x] Pinged the team for the package for their input.

Fixes https://github.com/conda-forge/nco-feedstock/issues/170
Fixes https://github.com/conda-forge/google-api-python-client-feedstock/issues/133
Fixes https://github.com/conda-forge/airflow-provider-great-expectations-feedstock/issues/5
Fixes https://github.com/conda-forge/google-cloud-pubsub-feedstock/issues/52
Fixes https://github.com/conda-forge/google-cloud-translate-feedstock/issues/44
Fixes https://github.com/conda-forge/google-cloud-language-feedstock/issues/32
Fixes https://github.com/conda-forge/google-cloud-kms-feedstock/issues/31
Fixes https://github.com/conda-forge/google-cloud-datastore-feedstock/issues/48
Fixes https://github.com/conda-forge/google-cloud-dataform-feedstock/issues/6
Fixes https://github.com/conda-forge/google-cloud-bigtable-feedstock/issues/47
Fixes https://github.com/conda-forge/google-cloud-vision-feedstock/issues/46

ping @conda-forge/nco 
ping @conda-forge/google-api-python-client

### CODE REVIEW

**Comment by xylar** [comment]
ping @conda-forge/airflow-provider-great-expectations

**Comment by xylar** [comment]
ping @conda-forge/google-cloud-pubsub

**Comment by xylar** [comment]
ping @conda-forge/google-cloud-translate

**Comment by xylar** [comment]
ping @conda-forge/google-cloud-language

**Comment by xylar** [comment]
ping @conda-forge/google-cloud-kms 
ping @conda-forge/google-cloud-datastore 
ping @conda-forge/google-cloud-dataform 
ping @conda-forge/google-cloud-bigtable

**Comment by xylar** [comment]
ping @conda-forge/google-cloud-vision

**Comment by xylar** [comment]
Thanks @chrisburr!  Probably not the last of these I'll submit but it's nice to get these fixed.

**Comment by jakirkham** [comment]
Think I've restarted CI for all of these, but could easily have missed one. Please feel free to retry any I missed

**Pull request merged**
